#Obstacle marking parameters
obstacle_range: 2.5
max_obstacle_height: 4.0
raytrace_range: 3.0

#Robot's footprint
footprint: [[-0.47, 0.18], [-0.47, -0.18], [0.47, -0.18],[0.47, 0.18]]

#Cost function parameters
inflation_radius: 0.2

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: scan, marking: true, clearing: true}
